### ISSUE TITLE
Status on Windows version, can I help?

### ISSUE THREAD

**Issue by EmbeddedSam** [donaldaverill/meteor-package-serialport#5]
I am not sure why this isn't working on Windows, could you possibly be a bit more specific on how we can make serial port work on meteor on Windows? Thanks also thanks for the current solution.

**Comment by donaldaverill** [comment]
I managed to publish to windows with the latest version of serialport (1.7.4), so let me know if it works for you. You may have to remove the package and then add it again.

**Comment by EmbeddedSam** [comment]
Just to confirm, I have re-added the module and it is working fine, thank you for the quick response and solution.
